local M = {}
vim.keymap.set('c', '<M-h>', '<Left>', { silent = false, desc = 'Left' })
vim.keymap.set('c', '<M-l>', '<Right>', { silent = false, desc = 'Right' })
vim.keymap.set('i', '<M-h>', '<Left>', { noremap = false, desc = 'Left' })
vim.keymap.set('i', '<M-j>', '<Down>', { noremap = false, desc = 'Down' })
vim.keymap.set('i', '<M-k>', '<Up>', { noremap = false, desc = 'Up' })
vim.keymap.set('i', '<M-l>', '<Right>', { noremap = false, desc = 'Right' })
vim.keymap.set('n', '<C-H>', '<C-w>h', { desc = 'Focus on left window' })
vim.keymap.set('n', '<C-J>', '<C-w>j', { desc = 'Focus on below window' })
vim.keymap.set('n', '<C-K>', '<C-w>k', { desc = 'Focus on above window' })
vim.keymap.set('n', '<C-L>', '<C-w>l', { desc = 'Focus on right window' })
vim.keymap.set("n", '<Esc>', "<cmd>noh<CR>", { desc = 'quit' })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true })
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true })
vim.keymap.set('t', '<M-h>', '<Left>', { desc = 'Left' })
vim.keymap.set('t', '<M-j>', '<Down>', { desc = 'Down' })
vim.keymap.set('t', '<M-k>', '<Up>', { desc = 'Up' })
vim.keymap.set('t', '<M-l>', '<Right>', { desc = 'Right' })
vim.keymap.set({ 'i', 'n' }, '<M-e>', '<End>', { desc = 'move to end of line' })
vim.keymap.set('i', '<M-b>', '<ESC>^i', { desc = 'move to beginning of line' })
vim.keymap.set('n', '<M-b>', '0', { desc = 'move to beginning of line' })
vim.keymap.set('n', ']]', '<cmd>lua Snacks.words.jump(1, 1)<CR>', { desc = 'Next Reference' }  )
vim.keymap.set('n', '[[', '<cmd>lua Snacks.words.jump(-1, 1)<CR>', { desc = 'Prev Reference' }  )

vim.keymap.set('n', '<C-Left>', '"<Cmd>vertical resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window width' })
vim.keymap.set('n', '<C-Down>', '"<Cmd>resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window height' })
vim.keymap.set('n', '<C-Up>', '"<Cmd>resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window height' })
vim.keymap.set('n', '<C-Right>', '"<Cmd>vertical resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window width' })

vim.keymap.set("n", '<leader>q', ":quit<CR>", { desc = 'quit' })
vim.keymap.set("n", '<leader>w', ":w<CR>", { desc = 'write' })
vim.keymap.set("n", '<leader>z', ":wq<CR>", { desc = 'write and quit' })
vim.keymap.set('n', "<leader><space>", "<cmd>lua Snacks.picker.smart()<CR>", { desc = "Smart Find Files" })

vim.keymap.set('n', "<leader>bf", "<cmd>lua Snacks.picker.buffers()<CR>", { desc = "find" })
vim.keymap.set("n", '<leader>bn', ":tabnext<CR>", { desc = 'next' })
vim.keymap.set("n", '<leader>bp', ":tabprevious<CR>", { desc = 'previous' })
vim.keymap.set("n", '<leader>bq', ":tabc<CR>", { desc = 'close' })
vim.keymap.set('n', "<leader>bx", "<cmd>lua Snacks.scratch()<CR>", { desc = "toggle Scratch Buffer" })
vim.keymap.set('n', "<leader>bX", "<cmd>lua Snacks.scratch.select()<CR>", { desc = "Select Scratch Buffer" })

vim.keymap.set("n", '<leader>ca', ":lua vim.lsp.buf.code_action() <CR>", { desc = 'apply action' })
vim.keymap.set("n", '<leader>cd', ":lua vim.lsp.buf.definition() <CR>", { desc = 'Goto Definition' })
vim.keymap.set("n", '<leader>cD', ":lua vim.lsp.buf.declaration() <CR>", { desc = 'Goto Declaration' })
vim.keymap.set("n", '<leader>ch', "<cmd>LspClangdSwitchSourceHeader<cr>", { desc = "Switch Source/Header (C/C++)" })
vim.keymap.set("n", '<leader>cI', "<cmd>ClangdSymbolInfo<cr>", { desc = "symbol info (C/C++)" })
vim.keymap.set("n", '<leader>ci', ":lua vim.lsp.buf.implementation() <CR>", { desc = 'list implementations' })
vim.keymap.set("n", '<leader>cm', "<cmd>ClangdMemoryUsage<cr>", { desc = "Memory Usage (C/C++)" })
vim.keymap.set("n", '<leader>cr', ":lua vim.lsp.buf.rename() <CR>", { desc = 'rename symbol' })
vim.keymap.set("n", '<leader>cR', ":lua vim.lsp.buf.references() <CR>", { desc = 'show references to symbol' })
vim.keymap.set("n", '<leader>ct', ":lua vim.lsp.buf.type_definition() <CR>", { desc = 'show type definition' })
vim.keymap.set("n", "<leader>cS", "<cmd>lua vim.lsp.buf.workspace_symbol()<CR>", { desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>csd", "<cmd>lua Snacks.picker.lsp_definitions()<CR>", { desc = "Definition" })
vim.keymap.set("n", "<leader>csD", "<cmd>lua Snacks.picker.lsp_declarations()<CR>", { desc = "Declaration" })
vim.keymap.set("n", "<leader>csi", "<cmd>lua Snacks.picker.lsp_implementations()<CR>", { desc = "Implementations" })
vim.keymap.set("n", '<leader>csr', "<cmd>lua Snacks.picker.lsp_references({ include_current = true, auto_confirm = false })<CR>", { nowait = true, desc = "References" })
vim.keymap.set("n", "<leader>css", "<cmd>lua Snacks.picker.lsp_symbols()<CR>", { desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>csS", "<cmd>lua Snacks.picker.lsp_workspace_symbols({ tree = true })<CR>", { desc = "LSP Workspace Symbols" })
vim.keymap.set('n', '<leader>cst', "<cmd>lua Snacks.picker.lsp_type_definitions()<CR>", { desc = "Type Definition" })

vim.keymap.set('n', "<leader>dD", "<cmd>lua Snacks.picker.diagnostics_buffer()<CR>", { desc = "Buffer Diagnostics" })
vim.keymap.set('n', "<leader>dd", "<cmd>lua Snacks.picker.diagnostics()<CR>", { desc = "Diagnostics" })
--[[ vim.keymap.set('n', "<leader>dt", "<cmd>LaunchTermDebug<CR>", { desc = "Start Debug Session" })
vim.keymap.set('n', "<leader>dF", "<cmd>Finish<CR>", { desc = "Finish" })
vim.keymap.set('n', "<leader>db", "<cmd>Break<CR>", { desc = "Break" })
vim.keymap.set('n', "<leader>dc", "<cmd>Clear<CR>", { desc = "Clear" })
vim.keymap.set('n', "<leader>de", "<cmd>Evaluate<CR>", { desc = "Evaluate" })
vim.keymap.set('n', "<leader>dc", "<cmd>Source<CR>", { desc = "goto Code" })
vim.keymap.set('n', "<leader>df", "<cmd>Finish<CR>", { desc = "Frame" })
vim.keymap.set('n', "<leader>dg", "<cmd>Gdb<CR>", { desc = "goto GDB" })
vim.keymap.set('n', "<leader>dn", "<cmd>Over<CR>", { desc = "Next" })
vim.keymap.set('n', "<leader>dp", "<cmd>Program<CR>", { desc = "goto Program" })
vim.keymap.set('n', "<leader>ds", "<cmd>Step<CR>", { desc = "Step" })
vim.keymap.set('n', "<leader>dv", "<cmd>Var<CR>", { desc = "goto Variables" }) ]]
vim.keymap.set('n', "<leader>dB", "<cmd>lua require('dap').step_back()<CR>", { desc = "Step Back" })
vim.keymap.set('n', "<leader>db", "<cmd>lua require('dap').toggle_breakpoint()<CR>", { desc = "Break" })
vim.keymap.set('n', "<leader>dc", "<cmd>lua require('dap').clear_breakpoints()<CR>", { desc = "Clear" })
vim.keymap.set('n', "<leader>dr", "<cmd>lua require('dap').continue()<CR>", { desc = "Continue or Run" })
vim.keymap.set('n', "<leader>df", "<cmd>lua require('dap').focus_frame()<CR>", { desc = "Frame" })
vim.keymap.set('n', "<leader>dh", "<cmd>lua require('dap.ui.widgets').hover() <CR>", { desc = "hover" })
vim.keymap.set('n', "<leader>dl", "<cmd>lua require('dap').goto_()<CR>", { desc = "goto line" })
vim.keymap.set('n', "<leader>ds", "<cmd>lua require('dap').step_into()<CR>", { desc = "Step into" })
vim.keymap.set('n', "<leader>dt", "<cmd>lua require('dapui').toggle()<CR>", { desc = "toggle dap ui" })
-- vim.keymap.set('n', "<leader>dr", "<cmd>lua require('dap').run()<CR>", { desc = "run" })
-- vim.keymap.set('n', "<leader>dn", "<cmd>lua require('dap').finish()<CR>", { desc = "Next" })
-- vim.keymap.set('n', "<leader>dc", "<cmd>lua require('dap').finish()<CR>", { desc = "goto Code" })
-- vim.keymap.set('n', "<leader>dg", "<cmd>lua require('dap').finish()<CR>", { desc = "goto GDB" })

vim.keymap.set('n', "<leader>fc", '<cmd>lua Snacks.picker.files({ cwd = vim.fn.stdpath("config") })<CR>', { desc = "Edit Config" })
vim.keymap.set('n', "<leader>ff", "<cmd>lua Snacks.picker.files({ hidden = true })<CR>", { desc = "Find" })
vim.keymap.set('n', "<leader>fr", "<cmd>lua Snacks.picker.recent()<CR>", { desc = "Recent" })
vim.keymap.set("n", '<leader>fS', ":SudaWrite<CR>", { desc = 'Suda write' })
vim.keymap.set("n", '<leader>fs', ":w<CR>", { desc = 'Save' })

vim.keymap.set('n', "<leader>gb", "<cmd>lua Snacks.picker.git_branches()<CR>", { desc = "Branches" })
vim.keymap.set('n', "<leader>gd", "<cmd>lua Snacks.picker.git_diff()<CR>", { desc = "Diff (Hunks)" })
vim.keymap.set('n', "<leader>gf", "<cmd>lua Snacks.picker.git_files()<CR>", { desc = "Find Files" })
vim.keymap.set('n', "<leader>gF", "<cmd>lua Snacks.picker.git_log_file()<CR>", { desc = "Log File" })
vim.keymap.set('n', "<leader>gl", "<cmd>lua Snacks.lazygit()<CR>", { desc = "Lazygit" })
vim.keymap.set('n', "<leader>gL", "<cmd>lua Snacks.picker.git_log()<CR>", { desc = "Log" })
vim.keymap.set('n', "<leader>gi", "<cmd>lua Snacks.picker.git_log_line()<CR>", { desc = "Log Line" })
vim.keymap.set('n', "<leader>gS", "<cmd>lua Snacks.picker.git_stash()<CR>", { desc = "Stash" })
vim.keymap.set('n', "<leader>gs", "<cmd>lua Snacks.picker.git_status()<CR>", { desc = "Status" })

vim.keymap.set("n", "<leader>he", "<cmd>NoiceSnacks<CR>", { desc = "search through errors" })
vim.keymap.set("n", "<leader>hf", function() Snacks.picker.help({ confirm = function(picker, item) picker:action("jump") end }) end, { desc = "Vim help" })
vim.keymap.set('n', "<leader>hk", "<cmd>lua Snacks.picker.keymaps({ plugs = true}) <CR>", { desc = "Keymaps" })
vim.keymap.set('n', "<leader>hm", "<cmd>lua Snacks.picker.man() <CR>", { desc = "Man pages" })
vim.keymap.set("n", "<leader>hl", "<cmd>NoiceLast<CR>", { desc = "show last error" })

vim.keymap.set("n", '<leader>mm', ":Mason<CR>", { desc = 'view mason' })
vim.keymap.set("n", '<leader>mp', "<cmd>lua vim.pack.update(nil, { offline = true })<CR>", { desc = 'show installed plugins' })
vim.keymap.set("n", '<leader>mu', "<cmd>lua vim.pack.update()<CR>", { desc = 'update plugins' })
vim.keymap.set("n", '<leader>md', "<cmd>PackRemove<CR>", { desc = 'delete plugins' })
vim.keymap.set("n", '<leader>mD', "<cmd>PackRemoveAllUnused<CR>", { desc = 'delete all inactive plugins' })

vim.keymap.set('n', "<leader>oe", "<cmd>lua MiniFiles.open()<CR>", { desc = "Open explorer" })
vim.keymap.set('n', "<leader>os", "<cmd>NvimTreeToggle<CR>", { desc = "Open sidebar" })
vim.keymap.set('n', "<leader>of", "<cmd>NvimTreeFindFile<CR>", { desc = "Open sidebar find file" })
vim.keymap.set('n', "<leader>oT", "<cmd>lua Snacks.terminal() <CR>", { desc = "Open terminal" })
vim.keymap.set('n', "<leader>ot", "<cmd>lua Snacks.terminal.toggle() <CR>", { desc = "Toggle Terminal" })
-- NOTE: if you have yazi installed and you want to use the yazi plugin
-- vim.keymap.set('n', '<leader>od', '<cmd>Yazi cwd<cr>', { desc = "Open the file manager in nvim's working directory" })
-- vim.keymap.set('n', '<leader>of', '<cmd>Yazi<cr>', { desc = 'Open yazi at
-- vim.keymap.set('n', '<c-y>', '<cmd>Yazi toggle<cr>', { desc = 'Resume the last yazi session' })

vim.keymap.set('n', "<leader>pf", "<cmd>ProjectSnacks<CR>", { desc = "Find Project" })
vim.keymap.set('n', "<leader>ph", "<cmd>ProjectHistory<CR>", { desc = "Project History" })
vim.keymap.set('n', "<leader>pr", "<cmd>ProjectRecents<CR>", { desc = "Recent Projects" })
vim.keymap.set('n', "<leader>ps", "<cmd>ProjectSession<CR>", { desc = "Project Sessions" })
vim.keymap.set('n', "<leader>pS", "<cmd>lua Snacks.picker.projects()<CR>", { desc = "Snacks Project Picker" })
vim.keymap.set('n', "<leader>pc", "<cmd>ProjectHealth<CR>", { desc = "Project Checkhealth" })

vim.keymap.set('n', "<leader>s:", "<cmd>lua Snacks.picker.command_history()<CR>", { desc = "Command History" })
vim.keymap.set('n', "<leader>sf", "<cmd>lua Snacks.picker.lines()<CR>", { desc = "in current file" })
vim.keymap.set('n', "<leader>sd", "<cmd>lua Snacks.picker.grep()<CR>", { desc = "in current directory" })
vim.keymap.set('n', "<leader>sg", "<cmd>lua Snacks.picker.grep_word()<CR>", { desc = "visual selection or word" })
vim.keymap.set('n', "<leader>sj", "<cmd>lua Snacks.picker.jumps() <CR>", { desc = "Jumps" })
vim.keymap.set('n', "<leader>su", "<cmd>lua Snacks.picker.undo()<CR>", { desc = "Undo History" })
return M
