map = vim.keymap.set
local fzf = require("fzf-lua")

map('c', '<M-h>', '<Left>', { silent = false, desc = 'Left' })
map('c', '<M-l>', '<Right>', { silent = false, desc = 'Right' })
map('i', '<M-h>', '<Left>', { noremap = false, desc = 'Left' })
map('i', '<M-j>', '<Down>', { noremap = false, desc = 'Down' })
map('i', '<M-k>', '<Up>', { noremap = false, desc = 'Up' })
map('i', '<M-l>', '<Right>', { noremap = false, desc = 'Right' })
map('n', '<C-H>', '<C-w>h', { desc = 'Focus on left window' })
map('n', '<C-J>', '<C-w>j', { desc = 'Focus on below window' })
map('n', '<C-K>', '<C-w>k', { desc = 'Focus on above window' })
map('n', '<C-L>', '<C-w>l', { desc = 'Focus on right window' })
map("n", '<Esc>', "<cmd>noh<CR>", { desc = 'quit' })
map('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true })
map('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true })
map('t', '<M-h>', '<Left>', { desc = 'Left' })
map('t', '<M-j>', '<Down>', { desc = 'Down' })
map('t', '<M-k>', '<Up>', { desc = 'Up' })
map('t', '<M-l>', '<Right>', { desc = 'Right' })
map({ 'i', 'n' }, '<M-e>', '<End>', { desc = 'move to end of line' })
map('i', '<M-b>', '<ESC>^i', { desc = 'move to beginning of line' })
map('n', '<M-b>', '0', { desc = 'move to beginning of line' })
map('n', ']]', function() require("illuminate.goto").goto_next_reference("wrapscan")end, { desc = 'Next Reference' }  )
map('n', '[[', function() require("illuminate.goto").goto_prev_reference("wrapscan")end, { desc = 'Prev Reference' }  )
map("n", "gd", function() fzf.lsp_definitions() end, { desc = "Goto Definition" })
map("n", "gD", function() fzf.lsp_declarations() end, { desc = "Goto Definition" })
map("n", 'gk', function() require("treesitter-context").go_to_context(vim.v.count1) end, { silent = true, desc = 'go to context hint' })
map('n', "grr", function() fzf.lsp_references() end, {desc = "References"})
map('n', "grs", function() fzf.lsp_document_symbols() end, {desc = "LSP Symbols"})
map('n', "grS", function() fzf.lsp_workspace_symbols() end, {desc = "LSP Workspace Symbols"})
map('n', "grd", function() fzf.lsp_definitions() end, {desc = "Definition"})
map('n', "grD", function() fzf.lsp_declarations() end, {desc = "Declaration"})
map('n', "gri", function() fzf.lsp_implementations() end, {desc = "Implementations"})
map('n', "grt", function() fzf.lsp_typedefs() end, {desc = "Type Definition"})
map('n', "gra", function() fzf.lsp_code_actions() end, {desc = "Code Actions"})
map('n', "grf", function() fzf.lsp_finder() end, {desc = "find"})
map("n", 'grI', "<cmd>ClangdSymbolInfo<cr>", { desc = "symbol info (C/C++)" })
map("n", 'grm', "<cmd>ClangdMemoryUsage<cr>", { desc = "Memory Usage (C/C++)" })
map("n", 'grh', "<cmd>ClangdSwitchSourceHeader<cr>", { desc = "Switch Source/Header (C/C++)" })
map('v', '<leader>s', ":'<,'>!sort<CR><CR>", { noremap = true, silent = true })

map('n', '<C-Left>', '"<Cmd>vertical resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window width' })
map('n', '<C-Down>', '"<Cmd>resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window height' })
map('n', '<C-Up>', '"<Cmd>resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window height' })
map('n', '<C-Right>', '"<Cmd>vertical resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window width' })

map("n", '<leader>q', ":quit<CR>", { desc = 'quit' })
map("n", '<leader>w', ":w<CR>", { desc = 'write' })
map("n", '<leader>z', ":wq<CR>", { desc = 'write and quit' })
map('n', "<leader><space>", function() fzf.vcs_files() end, {desc = "Project"})
map('n', '<leader><tab>', function() fzf.resume() end, {desc = "Reopen last search"})

map("n", "<leader>bf", [[:lua require"fzf-lua".buffers()<CR>]], { desc = "search buffers" })
map("n", '<leader>bn', "<cmd>bnext<CR>", { desc = 'next' })
map("n", '<leader>bp', "<cmd>bprevious<CR>", { desc = 'previous' })
map("n", '<leader>bq', "<cmd>bdelete<CR>", { desc = 'close' })
map("n", '<leader>bN', "<cmd>tabnext<CR>", { desc = 'tab next' })
map("n", '<leader>bP', "<cmd>tabprevious<CR>", { desc = 'tab previous' })
map("n", '<leader>bQ', "<cmd>tabc<CR>", { desc = 'tab close' })

map('n', '<leader>ca', function() fzf.lsp_code_actions() end, {desc = "Code Actions"})
map('n', '<leader>cc', ":Clean <CR>", { desc = 'rebuild' })
map('n', '<leader>cd', function() fzf.lsp_definitions() end, {desc = "Definition"})
map('n', '<leader>cf', function() fzf.lsp_finder() end, {desc = "find"})
map('n', '<leader>ch', "<cmd>ClangdSwitchSourceHeader<cr>", { desc = "Switch Source/Header (C/C++)" })
map('n', '<leader>ci', function() fzf.lsp_implementations() end, {desc = "Implementations"})
map('n', '<leader>cm', "<cmd>ClangdMemoryUsage<cr>", { desc = "Memory Usage (C/C++)" })
map('n', '<leader>cr', function() fzf.lsp_references() end, {desc = "References"})
map('n', '<leader>cs', function() fzf.lsp_document_symbols() end, {desc = "LSP Symbols"})
map('n', '<leader>ct', function() fzf.lsp_typedefs() end, {desc = "Type Definition"})
map('n', '<leader>cD', function() fzf.lsp_declarations() end, {desc = "Declaration"})
map('n', '<leader>cI', "<cmd>ClangdSymbolInfo<cr>", { desc = "symbol info (C/C++)" })
map('n', '<leader>cR', ":lua vim.lsp.buf.rename() <CR>", { desc = 'rename symbol' })
map('n', '<leader>cS', function() fzf.lsp_workspace_symbols() end, {desc = "LSP Workspace Symbols"})

map('n', '<leader>dD', function() fzf.diagnostics_workspace() end, {desc = "File Diagnostics"})
map('n', '<leader>dd', function() fzf.diagnostics_document() end, {desc = "Workspace Diagnostics"})
map('n', "<leader>dt", "<cmd>LaunchTermDebug<CR>", { desc = "Start Debug Session" })
map('n', "<leader>db", "<cmd>Break<CR>", { desc = "Break" })
map('n', "<leader>dc", "<cmd>Clear<CR>", { desc = "Clear" })
map('n', "<leader>de", "<cmd>Evaluate<CR>", { desc = "Evaluate" })
map('n', "<leader>dc", "<cmd>Source<CR>", { desc = "goto Code" })
map('n', "<leader>df", "<cmd>Finish<CR>", { desc = "Finish" })
map('n', "<leader>dg", "<cmd>Gdb<CR>", { desc = "goto GDB" })
map('n', "<leader>dn", "<cmd>Over<CR>", { desc = "Next" })
map('n', "<leader>dp", "<cmd>Program<CR>", { desc = "goto Program" })
map('n', "<leader>ds", "<cmd>Step<CR>", { desc = "Step" })
map('n', "<leader>dv", "<cmd>Var<CR>", { desc = "goto Variables" })

map('n', "<leader>fc", function() fzf.files({ cwd = vim.fn.stdpath("config")}) end, {desc = "Edit Config"})
map('n', '<leader>fd', function() fzf.zoxide() end, { desc = 'find dir' })
map('n', '<leader>ff', [[:lua require"fzf-lua".files()<CR>]], { desc = 'find files' })
map("n", "<leader>fr", [[:lua require"fzf-lua".oldfiles()<CR>]], { desc = "recent" })
map("n", '<leader>fS', ":SudaWrite<CR>", { desc = 'Suda write' })
map("n", '<leader>fs', ":w<CR>", { desc = 'Save' })
map('n', '<leader>ft', [[:lua require"fzf-lua".tabs()<CR>]], { desc = 'search tabs' })

map('n', "<leader>gb", function() fzf.git_branches() end, {desc = "Branches"})
map('n', "<leader>gc", function() fzf.git_commits() end, {desc = "Commit Log"})
map('n', "<leader>gd", function() fzf.git_diff() end, {desc = "Diff"})
map('n', "<leader>gf", function() fzf.git_files() end, {desc = "Files"})
map('n', "<leader>gh", function() fzf.git_hunks() end, {desc = "Hunks"})
map('n', "<leader>gC", function() fzf.git_bcommits() end, {desc = "Buffer Commit Log"})
map('n', "<leader>gl", "<cmd>LazyGit<CR>", { desc = "Lazygit" })
map('n', "<leader>gr", function() fzf.git_reflog() end, {desc = "Reflog"})
map('n', "<leader>gs", function() fzf.git_status() end, {desc = "Status"})
map('n', "<leader>gS", function() fzf.git_stash() end, {desc = "Stash"})
map('n', "<leader>gw", function() fzf.git_worktrees() end, {desc = "Worktrees"})

map('n', '<leader>hf', [[:lua require"fzf-lua".helptags()<CR>]], { desc = 'search help tags' })
map('n', "<leader>hk", function() fzf.keymaps() end, {desc = "Keymaps"})
map('n', "<leader>hm", function() fzf.manpages() end, {desc = "Manpages"})
map("n", "<leader>hl", "<cmd>NoiceLast<CR>", { desc = "show last error" })

map("n", '<leader>mm', ":Mason<CR>", { desc = 'view mason' })
map("n", '<leader>mp', "<cmd>lua vim.pack.update(nil, { offline = true })<CR>", { desc = 'show installed plugins' })
map("n", '<leader>mu', "<cmd>lua vim.pack.update()<CR>", { desc = 'update plugins' })
map('n', "<leader>mf", function() fzf.packadd() end, {desc = "fzf packadd"})
map("n", '<leader>md', "<cmd>PackRemove<CR>", { desc = 'delete plugins' })
map("n", '<leader>mD', "<cmd>PackRemoveAllUnused<CR>", { desc = 'delete all inactive plugins' })

map('n', "<leader>oo", "<cmd>Oil<CR>", { desc = "Open explorer" })
map('n', '<leader>ot', "<cmd>ToggleTerm size=13<CR>", { desc = "Open terminal" })
-- NOTE: if you have yazi installed and you want to use the yazi plugin
-- vim.keymap.set('n', '<leader>od', '<cmd>Yazi cwd<cr>', { desc = "Open the file manager in nvim's working directory" })
-- vim.keymap.set('n', '<leader>of', '<cmd>Yazi<cr>', { desc = 'Open yazi at
-- vim.keymap.set('n', '<c-y>', '<cmd>Yazi toggle<cr>', { desc = 'Resume the last yazi session' })

map('n', "<leader>pf", "<cmd>Project fzf-lua<CR>", { desc = "Find Project" })
map('n', "<leader>ph", "<cmd>Project history<CR>", { desc = "Project History" })
map('n', "<leader>pr", "<cmd>Project recents<CR>", { desc = "Recent Projects" })
map('n', "<leader>ps", "<cmd>Project session<CR>", { desc = "Project Sessions" })
map('n', "<leader>pc", "<cmd>Project health<CR>", { desc = "Project Checkhealth" })

map('n', "<leader>s:", function() fzf.command_history() end, { desc = "Jumps" })
map('n', "<leader>sf", function() fzf.blines() end, {desc = "Current Buffer"})
map('n', "<leader>sd", function() fzf.grep_project() end, {desc = "Grep Project"})
map('n', '<leader>sh', [[:lua require"fzf-lua".history()<CR>]], { desc = 'History' })
map('n', "<leader>sg", function() fzf.grep_cword() end, { desc = "Jumps" })
map('n', "<leader>sj", function() fzf.jumps() end, { desc = "Jumps" })
map('n', "<leader>sl", function() fzf.loclist() end, {desc = "Location List"})
map('n', "<leader>sq", function() fzf.quickfix() end, {desc = "Quickfix List"})
map('n', "<leader>sQ", function() fzf.quickfix_stack() end, {desc = "Quickfix Stack"})
map('n', "<leader>st", function() fzf.tags() end, {desc = "Tags"})
map('n', "<leader>su", function() fzf.undotree() end, {desc = "Undo History"})
