" Name:         sorbet
" Description:  A shallow grave, a monument to the ruined age.
" Author:       Maxence Weynans <neutaaaaan@gmail.com>
" Maintainer:   Maxence Weynans <neutaaaaan@gmail.com>
" Website:      https://github.com/vim/colorschemes
" License:      Vim License (see `:help license`)`
" Last Change:  2025 Jan 07

" Generated by Colortemplate v2.2.3

set background=dark

" hi clear
source $VIMRUNTIME/colors/vim.lua " Nvim: revert to Vim default color scheme
let g:colors_name = 'onedark'

let s:t_Co = &t_Co

hi! link Terminal Normal
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
hi! link PopupSelected PmenuSel
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link ErrorMsg Error
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor
hi! link debugPC CursorLine
hi! link DiagnosticError DiagnosticVirtualTextError
hi! link DiagnosticError DiagnosticVirtualLinesError
hi! link DiagnosticError DiagnosticUnderlineError
hi! link DiagnosticError DiagnosticFloatingError
hi! link DiagnosticError DiagnosticSignError
hi! link DiagnosticWarn DiagnosticVirtualTextWarn
hi! link DiagnosticWarn DiagnosticVirtualLinesWarn
hi! link DiagnosticWarn DiagnosticUnderlineWarn
hi! link DiagnosticWarn DiagnosticFloatingWarn
hi! link DiagnosticWarn DiagnosticSignWarn
hi! link DiagnosticInfo DiagnosticVirtualTextInfo
hi! link DiagnosticInfo DiagnosticVirtualLinesInfo
hi! link DiagnosticInfo DiagnosticUnderlineInfo
hi! link DiagnosticInfo DiagnosticFloatingInfo
hi! link DiagnosticInfo DiagnosticSignInfo
hi! link DiagnosticHint DiagnosticVirtualTextHint
hi! link DiagnosticHint DiagnosticVirtualLinesHint
hi! link DiagnosticHint DiagnosticUnderlineHint
hi! link DiagnosticHint DiagnosticFloatingHint
hi! link DiagnosticHint DiagnosticSignHint
hi! link DiagnosticOk DiagnosticVirtualTextOk
hi! link DiagnosticOk DiagnosticVirtualLinesOk
hi! link DiagnosticOk DiagnosticUnderlineOk
hi! link DiagnosticOk DiagnosticFloatingOk
hi! link DiagnosticOk DiagnosticSignOk

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#3F4451', '#E06C75', '#98C379', '#D19A66', '#61AFEF', '#C678DD', '#56B6C2', '#D7DAE0', '#4F5666', '#BE5046', '#A5E075', '#E5C07B', '#4DC4FF', '#DE73FF', '#4CD1E0', '#E6E6E6']
  " Nvim uses g:terminal_color_{0-15} instead
  for i in range(g:terminal_ansi_colors->len())
    let g:terminal_color_{i} = g:terminal_ansi_colors[i]
  endfor
endif

hi DiagnosticError guifg=#E06C75
hi DiagnosticWarn guifg=#D19A66
hi DiagnosticInfo guifg=#ABB2BF
hi DiagnosticHint guifg=#D7DAE0
hi DiagnosticOk guifg=#98C379
hi Normal guifg=#ABB2BF guibg=#282C34 gui=NONE cterm=NONE
hi Added guifg=#98C379 guibg=NONE gui=NONE cterm=NONE
hi Changed guifg=#61AFEF guibg=NONE gui=NONE cterm=NONE
hi Removed guifg=#E06C75  guibg=NONE gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#3F4451 gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE

hi CurSearch guifg=#E5C07B guibg=#4F5666 gui=reverse cterm=reverse
hi IncSearch guifg=#D19A66 guibg=#282C34 gui=reverse cterm=reverse,bold,underline
hi Search guifg=#D19A66 guibg=#282C34 gui=reverse cterm=reverse

hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
hi CursorColumn guifg=NONE guibg=#3F4451 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#21242c gui=NONE cterm=NONE
hi CursorLineNr guifg=#D7DAE0 guibg=#21242c gui=NONE cterm=NONE

hi DiffAdd guifg=#A5E075 guibg=#282C34 gui=reverse cterm=reverse  
hi DiffChange guifg=#61AFEF guibg=#282C34 gui=reverse cterm=reverse
hi DiffDelete guifg=#BE5046 guibg=#282C34 gui=reverse cterm=reverse
hi DiffText guifg=#DE73FF guibg=#282C34 gui=reverse cterm=reverse

hi Directory guifg=#D7DAE0 guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#4F5666 guibg=NONE gui=NONE cterm=NONE
hi FoldColumn guifg=#4F5666 guibg=NONE gui=NONE cterm=NONE
hi Folded guifg=#4F5666 guibg=#282C34 gui=NONE cterm=NONE
hi LineNr guifg=#60687C guibg=NONE gui=NONE cterm=NONE 

hi MatchParen guifg=#DE73FF guibg=NONE gui=bold cterm=bold 
hi ModeMsg guifg=#ABB2BF guibg=NONE gui=bold cterm=bold 
hi MoreMsg guifg=#D7DAE0 guibg=NONE gui=NONE cterm=NONE 
hi NonText guifg=#4F5666 guibg=NONE gui=NONE cterm=NONE

hi Pmenu guifg=#D7DAE0 guibg=#282C34 gui=NONE cterm=NONE
hi PmenuMatch guifg=#BE5046 guibg=#282C34 gui=NONE cterm=NONE  
hi PmenuExtra guifg=#D7DAE0 guibg=#282C34 gui=NONE cterm=NONE
hi PmenuKind guifg=#D7DAE0 guibg=#282C34 gui=bold cterm=bold
hi PmenuSbar guifg=#D7DAE0 guibg=#282C34 gui=NONE cterm=NONE 
hi PmenuSel guifg=#C678DD guibg=#3F4451 gui=NONE cterm=NONE
hi PmenuMatchSel guifg=#BE5046 guibg=#D7DAE0 gui=bold cterm=bold
hi PmenuExtraSel guifg=#282C34 guibg=#D7DAE0 gui=NONE cterm=NONE
hi PmenuKindSel guifg=#282C34 guibg=#D7DAE0 gui=bold cterm=bold
hi PmenuThumb guifg=#dadada guibg=#4F5666 gui=NONE cterm=NONE

hi Question guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi QuickFixLine guifg=#DE73FF guibg=#282C34 gui=reverse cterm=reverse
hi SignColumn guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#5f5f87 guibg=NONE gui=bold cterm=bold

hi SpellBad guifg=#d75f5f guibg=NONE guisp=#d75f5f gui=undercurl cterm=underline
hi SpellCap guifg=#4CD1E0 guibg=NONE guisp=#4CD1E0 gui=undercurl cterm=underline 
hi SpellLocal guifg=#C678DD guibg=NONE guisp=#C678DD gui=undercurl cterm=underline
hi SpellRare guifg=#56B6C2 guibg=NONE guisp=#56B6C2 gui=undercurl cterm=underline 

"#21242c
hi StatusLine guifg=#C678DD guibg=#282C34 gui=bold cterm=bold
hi StatusLineNC guifg=#3F4451 guibg=#282C34 gui=reverse cterm=reverse
hi TabLine guifg=#282C34 guibg=#C678DD gui=reverse cterm=reverse
hi TabLineFill guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi TabLineSel guifg=#282C34 guibg=#C678DD gui=bold cterm=bold
hi Title guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi VertSplit guifg=#4F5666 guibg=NONE gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#274d5c gui=NONE cterm=bold
hi VisualNOS guifg=NONE guibg=#363841 gui=NONE cterm=NONE
hi WarningMsg guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#4F5666 guibg=#3F4451 gui=bold cterm=bold

hi Comment guifg=#60687C guibg=NONE gui=italic cterm=italic
hi Constant guifg=#98C379 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#363841 guibg=#d75f5f gui=bold,reverse cterm=bold,reverse
hi Identifier guifg=#ABB2BF guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#ABB2BF guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#C678DD guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#E06C75 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#E6E6E6 guibg=NONE gui=NONE cterm=bold
hi String guifg=#61AFEF guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#E6E6E6 guibg=NONE gui=bold,reverse cterm=bold,reverse
hi Type guifg=#D19A66 guibg=NONE gui=NONE cterm=bold
hi Underlined guifg=#E6E6E6 guibg=NONE gui=underline cterm=underline

hi CursorIM guifg=#282C34 guibg=#98C379 gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#282C34 gui=NONE cterm=NONE
hi ToolbarButton guifg=#dadada guibg=#282C34 gui=bold cterm=bold
hi debugBreakpoint guifg=#3F4451 guibg=#282C34 gui=bold,reverse cterm=bold,reverse

if s:t_Co >= 256
  hi Normal ctermfg=253 ctermbg=233 cterm=NONE
  hi Added ctermfg=113 ctermbg=NONE cterm=NONE
  hi Changed ctermfg=110 ctermbg=NONE cterm=NONE
  hi Removed ctermfg=167 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CurSearch ctermfg=207 ctermbg=16 cterm=reverse
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLineNr ctermfg=189 ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=35 ctermbg=16 cterm=reverse
  hi DiffChange ctermfg=111 ctermbg=16 cterm=reverse
  hi DiffDelete ctermfg=161 ctermbg=16 cterm=reverse
  hi DiffText ctermfg=213 ctermbg=16 cterm=reverse
  hi Directory ctermfg=253 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=60 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=103 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=60 ctermbg=233 cterm=NONE
  hi IncSearch ctermfg=214 ctermbg=16 cterm=reverse
  hi LineNr ctermfg=60 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=253 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=253 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=242 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=16 ctermbg=248 cterm=NONE
  hi PmenuMatch ctermfg=161 ctermbg=248 cterm=NONE
  hi PmenuExtra ctermfg=16 ctermbg=248 cterm=NONE
  hi PmenuKind ctermfg=16 ctermbg=248 cterm=bold
  hi PmenuSbar ctermfg=242 ctermbg=60 cterm=NONE
  hi PmenuSel ctermfg=16 ctermbg=189 cterm=NONE
  hi PmenuMatchSel ctermfg=161 ctermbg=189 cterm=bold
  hi PmenuExtraSel ctermfg=16 ctermbg=189 cterm=NONE
  hi PmenuKindSel ctermfg=16 ctermbg=189 cterm=bold
  hi PmenuThumb ctermfg=253 ctermbg=189 cterm=NONE
  hi Question ctermfg=253 ctermbg=NONE cterm=NONE
  hi QuickFixLine ctermfg=207 ctermbg=16 cterm=reverse
  hi Search ctermfg=39 ctermbg=16 cterm=reverse
  hi SignColumn ctermfg=253 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=60 ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=110 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=140 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=73 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=16 ctermbg=189 cterm=bold
  hi StatusLineNC ctermfg=103 ctermbg=16 cterm=reverse
  hi TabLine ctermfg=103 ctermbg=16 cterm=reverse
  hi TabLineFill ctermfg=253 ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=16 ctermbg=189 cterm=bold
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=60 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=214 ctermbg=16 cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=237 cterm=NONE
  hi WarningMsg ctermfg=253 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=189 ctermbg=233 cterm=bold
  hi Comment ctermfg=140 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=167 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=16 cterm=bold,reverse
  hi Identifier ctermfg=113 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=253 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=110 ctermbg=NONE cterm=NONE
  hi Special ctermfg=73 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
  hi String ctermfg=179 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=79 ctermbg=NONE cterm=bold,reverse
  hi Type ctermfg=110 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=253 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=16 ctermbg=154 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=16 cterm=NONE
  hi ToolbarButton ctermfg=253 ctermbg=16 cterm=bold
  hi debugBreakpoint ctermfg=103 ctermbg=16 cterm=bold,reverse
  unlet s:t_Co
  finish
endif

if s:t_Co >= 16
  hi CurSearch ctermfg=magenta ctermbg=black cterm=reverse
  hi EndOfBuffer ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi Folded ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=yellow ctermbg=black cterm=reverse
  hi LineNr ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi NonText ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=darkgrey ctermbg=NONE cterm=reverse
  hi Search ctermfg=cyan ctermbg=black cterm=reverse
  hi SpecialKey ctermfg=darkgrey ctermbg=NONE cterm=bold
  hi StatusLineNC ctermfg=darkgrey ctermbg=NONE cterm=reverse
  hi TabLine ctermfg=darkgrey ctermbg=NONE cterm=reverse
  hi VertSplit ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=black cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=black cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=black cterm=reverse
  hi DiffText ctermfg=darkmagenta ctermbg=black cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuMatch ctermfg=NONE ctermbg=darkred cterm=reverse
  hi PmenuExtra ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuKind ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuMatchSel ctermfg=darkred ctermbg=NONE cterm=bold
  hi PmenuExtraSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuKindSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=standout
  hi QuickFixLine ctermfg=darkmagenta ctermbg=black cterm=reverse
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=darkred ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=black cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi Comment ctermfg=darkmagenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=darkred ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=black cterm=bold,reverse
  hi Identifier ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Special ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Statement ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi String ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=darkgreen ctermbg=black cterm=bold,reverse
  hi Type ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi debugBreakpoint ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  unlet s:t_Co
  finish
endif

if s:t_Co >= 8
  hi CurSearch ctermfg=darkmagenta ctermbg=black cterm=reverse
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=darkyellow ctermbg=black cterm=reverse
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Search ctermfg=darkcyan ctermbg=black cterm=reverse
  hi SpecialKey ctermfg=NONE ctermbg=NONE cterm=bold
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=black cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=black cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=black cterm=reverse
  hi DiffText ctermfg=darkmagenta ctermbg=black cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuMatch ctermfg=NONE ctermbg=darkred cterm=reverse
  hi PmenuExtra ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuKind ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuMatchSel ctermfg=darkred ctermbg=NONE cterm=bold
  hi PmenuExtraSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuKindSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=standout
  hi QuickFixLine ctermfg=darkmagenta ctermbg=black cterm=reverse
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=darkred ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=black cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi Comment ctermfg=darkmagenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=darkred ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=black cterm=bold,reverse
  hi Identifier ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Special ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Statement ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi String ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=darkgreen ctermbg=black cterm=bold,reverse
  hi Type ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi debugBreakpoint ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  unlet s:t_Co
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi CurSearch term=reverse
  hi CursorLineFold term=underline
  hi CursorLineSign term=underline
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co
  finish
endif

" Background: dark
" Color: guibg         #161821           233               black
" Color: statusline    #d7d7ff           189               white
" Color: statuslineNC  #8787af           103               grey
" Color: darkuipurple  #5f5f87           60                grey
" Color: dark0         #282C34           16                black
" Color: dark1         #d75f5f           167               darkred
" Color: dark2         #87d75f           113               darkgreen
" Color: dark3         #d7af5f           179               darkyellow
" Color: dark4         #4DC4FF           110               darkblue
" Color: dark5         #C678DD           140               darkmagenta
" Color: dark6         #5fafaf           73                darkcyan
" Color: dark7         #dadada           253               grey
" Color: dark8         #707070           242               darkgrey
" Color: dark9         #ff5f5f           203               red
" Color: dark10        #87ff5f           119               green
" Color: dark11        #ffd75f           221               yellow
" Color: dark12        #87d7ff           117               blue
" Color: dark13        #d787ff           177               magenta
" Color: dark14        #5fd7d7           80                cyan
" Color: dark15        #ffffff           231               white
" Color: diffred       #d7005f           161               darkred
" Color: diffgreen     #00af5f           35                darkgreen
" Color: diffblue      #87afff           111               darkblue
" Color: diffpink      #ff87ff           213               darkmagenta
" Color: uipink        #ff00af           199               magenta
" Color: uilime        #afff00           154               green
" Color: uiteal        #5fd7af           79                green
" Color: uiblue        #00afff           39                blue
" Color: uipurple      #af00ff           129               darkmagenta
" Color: uiamber       #ffaf00           214               darkyellow
" Color: uiblack       #363841           237               darkgrey
" Color: yasogrey      #262831           235               black
" Color: linenrblack   #585858           240               darkgrey
" Color: uicursearch   #ff5fff           207               magenta
" Color: invisigrey    #ABB2BF           248               darkgrey
" Color: errorred      #ff5f5f           203               red
" Term colors: dark0 dark1 dark2 dark3 dark4 dark5 dark6 dark7
" Term colors: dark8 dark9 dark10 dark11 dark12 dark13 dark14 dark15
" vim: et ts=8 sw=2 sts=2
