Gh = function(x)
  return 'https://github.com/' .. x
end

require('plugins.mini')
require('plugins.onedark')
require('plugins.oil')
require('plugins.project')
require('plugins.treesitter')
require('plugins.indent-blankline')
require('plugins.lualine')
require('plugins.colorizer')
require('plugins.todo-comments')
require('plugins.nvim-lsp')
require('plugins.inlay-hints')
require('plugins.clangd_extensions')
-- require('plugins.nvim-cmp')
require('plugins.fidget')
require('plugins.conform')
require('plugins.comment')
require('plugins.vim-suda')
require('plugins.zen-mode')
require('plugins.toggleterm')
require('plugins.whichkey')
