Gh = function(x)
  return 'https://github.com/' .. x
end

require('plugins.mini')
require('plugins.onedark')
require('plugins.nvim-tree')
require('plugins.project')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.colorizer')
require('plugins.todo-comments')
require('plugins.nvim-lsp')
require('plugins.inlay-hints')
require('plugins.clangd_extensions')
require('plugins.fidget')
require('plugins.mason')
require('plugins.conform')
require('plugins.comment')
require('plugins.vim-suda')
-- require('plugins.neocodium')
-- require('plugins.dap')
require('plugins.rust')
-- require('plugins.haskell')
